/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#cfe5ff",
        "surface": "#fcf9f8",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0f0",
        "surface-container": "#f0eded",
        "on-surface-variant": "#41474f",
        "outline": "#717880",
        "background": "#fcf9f8",
        "on-surface": "#1b1c1c",
        "secondary-container": "#b3f585",
        "inverse-primary": "#98cbff",
        "primary-fixed-dim": "#98cbff",
        "on-error": "#ffffff",
        "surface-container-highest": "#e4e2e1",
        "surface-dim": "#dcd9d9",
        "secondary": "#336b07",
        "surface-tint": "#136299",
        "primary-container": "#5b9bd5",
        "outline-variant": "#c1c7d1",
        "surface-container-high": "#eae7e7",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#7f5600",
        "surface-variant": "#e4e2e1",
        "secondary-fixed-dim": "#98d86c",
        "primary": "#136299",
        "secondary-fixed": "#b3f585",
        "on-primary-container": "#003151",
        "surface-bright": "#fcf9f8",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f6f3f2",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-background": "#1b1c1c",
        "tertiary-fixed": "#ffddae",
        "tertiary-fixed-dim": "#f9bc58",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001d33",
        "on-secondary-fixed": "#0a2100",
        "secondary-fixed": "#b3f585",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-1": "8px",
        "space-2": "16px",
        "space-3": "24px",
        "space-4": "32px",
        "space-6": "48px",
        "space-10": "80px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["56px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "1.25", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", fontWeight: "600" }],
        "caption": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}